In [5]:
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt 
# import statistics as st

in_data = loadmat('movie.mat')
#loadmat() loads a matlab workspace into a python dictionary, where the names of the variables are the keys 
#in the dictionary.  To see what variables are loaded, uncomment the line below: 
print([key for key in in_data])

M = in_data['M']
print(M)

['__header__', '__version__', '__globals__', 'M', 'ans']
[[ 4  7  2  8  7  4  2]
 [ 9  3  5  6 10  5  5]
 [ 4  8  3  7  6  4  1]
 [ 9  2  6  5  9  5  4]
 [ 4  9  2  8  7  4  1]]


In [3]:
np.linalg.matrix_rank(M)

5

In [19]:
# M_T = M.T
# print(M_T)
avg_M = [list(M.mean(0))]*5
print(avg_M)
avg_ls = list(M.mean(0))
avg_ls

[[6.0, 5.8, 3.6, 6.8, 7.8, 4.4, 2.6], [6.0, 5.8, 3.6, 6.8, 7.8, 4.4, 2.6], [6.0, 5.8, 3.6, 6.8, 7.8, 4.4, 2.6], [6.0, 5.8, 3.6, 6.8, 7.8, 4.4, 2.6], [6.0, 5.8, 3.6, 6.8, 7.8, 4.4, 2.6]]


[6.0, 5.8, 3.6, 6.8, 7.8, 4.4, 2.6]

In [18]:
cons = (5)**(0.5)
w1_T = [x * cons for x in avg_ls]
w1_T

[13.416407864998739,
 12.96919426949878,
 8.049844718999244,
 15.20526224699857,
 17.44133022449836,
 9.838699100999076,
 5.813776741499454]

In [20]:
np.subtract(M, avg_M)

array([[-2. ,  1.2, -1.6,  1.2, -0.8, -0.4, -0.6],
       [ 3. , -2.8,  1.4, -0.8,  2.2,  0.6,  2.4],
       [-2. ,  2.2, -0.6,  0.2, -1.8, -0.4, -1.6],
       [ 3. , -3.8,  2.4, -1.8,  1.2,  0.6,  1.4],
       [-2. ,  3.2, -1.6,  1.2, -0.8, -0.4, -1.6]])

f) Do you see any patterns in the residual? Briefly describe them qualitatively.

Yes, there is a noticeable pattern in the residuals. It appears that individuals who favor sci-fi movies tend to have positive residuals for sci-fi movies (1st, 3rd, and 5th), while showing negative residuals for romance movies, and vice versa.